name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: /Dai2aDollar/  
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/d2ad

permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.